### ISSUE TITLE
error while loading shared libraries: libthai.so.0

### ISSUE THREAD

**Issue by lch361** [kanriapp/kanri#656]
**Describe the bug**
AppImage seems to depend on external libthai library, which contradicts to the AppImage definition of being a Linux executable without dependencies.

**To Reproduce**
1. Download [Kanri 0.7.1 amd64 AppImage](https://github.com/kanriapp/kanri/releases/download/app-v0.7.1/kanri_0.7.1_amd64.AppImage).
2. Try to execute it.
3. Receive `kanri: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory` if you don't have the library.

**Expected behavior**
Dependency-free AppImage.

**Desktop**
 - Linux.

**Comment by trobonox** [comment]
Thanks for reporting this issue. All builds of Kanri are handled by the application framework it is built with, Tauri. This issue seems to be a well known one for Tauri and apparently has been fixed, but it's not part of the 0.7.1 release because this fix has been quite recent. 

I am unable to be 100% certain that it's fixed, but the next release of Kanri should not have this issue anymore. This means that either you wait a little longer until it's out, or try some kind of workaround until then (install the library if you can or build the app yourself, etc.).

**Comment by lch361** [comment]
Thanks for the answer. Glad to hear that it's going to be fixed. Yep, I already built and installed the libthai library externally to enjoy the Kanri app - no other missing libraries detected.

**Comment by trobonox** [comment]
Release v0.8 is out now, so hopefully the issue should be fixed. If anyone wants to try and share their experiences, feel free. If no other person reports this to be an issue anymore, I will close this issue soon.

**Comment by lch361** [comment]
Excellent. Now the program works even with libthai removed from the system. The issue is solved now 👍🏻
