### ISSUE TITLE
Can't install kanri

### ISSUE THREAD

**Issue by lyndsay9968** [kanriapp/kanri#710]
**Describe the bug**
Installation fails on WebView2.

**To Reproduce**
1. Start installation
2. Wait

**Expected behavior**
Installation success.

**Screenshots**

> Downloading WebView2 bootstrapper...
WebView2 bootstrapper downloaded successfully
Installing WebView2...
Execute: C:\Users\lyndsay9968\AppData\Local\Temp\MicrosoftEdgeWebview2Setup.exe /silent /install
Error: Installing WebView2 failed with exit code 1
Failed to install WebView2! The app can't run without it. Try restarting the installer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser not applicable
 - Version not applicable

**Comment by lyndsay9968** [comment]
I tried to run the MicrosoftEdgeWebview2Setup.exe file manually, but absolutely nothing happens. The windows system is fully up to date and does not find any updates. Edge installed. Local account. No Windows Store.

**Comment by trobonox** [comment]
Sorry about this happening. This is because Kanri relies on WebView2 for displaying the app user interface and on older or stripped down versions of Windows 10 it might not be installed (all recent versions of Windows 10 or 11 should have it).

Did you have an internet connection available while installing Kanri? If not, you can download WebView2 directly from Microsoft and put it on some external drive to install it: https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH

I am not including it in the normal Kanri installer because it would make the file a lot larger and most people either have WebView2 installed already or have an internet connection available in the installation process.

If you have any questions or need more help, please let me know.

**Comment by lyndsay9968** [comment]
Problem solved. The cause was what a tangled mess windows is these days, where installing webview requires not only the installer, but also 10 services and 20 processes that crash silently without any error message if even one is blocked by the firewall. From loved to hated in 10 years.
