### ISSUE TITLE
Add live sync for individual boards

### ISSUE THREAD

**Issue by philion** [kanriapp/kanri#738]
I would like to sync my Kanri boards with an external source, like an API call. 

This would use the same format as (for example) Trello, but changes can be synced bidirectionally:
- Changes in the kanri board update the external system
- Changes in the external system update the kanri board

Specific changes:
- Import & Export settings get additional "Sync URL" field.
- It is assumed that all auth creds can fit into the URL.
- On a regular interval (say 5 minutes, or add an additional setting field), the URL is invoked:
  - the latest version of the board is queried
  - compared to the current on-disk version
  - updates are applied to on-disk version
  - updates that have been made on-disk are synced back to the external version.

**Comment by trobonox** [comment]
External sync is currently out of scope because there are essential features missing and I want to make the app the best it can be in its current offline-only form. 
Moreover, I have experimented with the idea of enabling sync but have ran into lots of headaches with merge issues and how to do seamless sync even when the app might go offline at times.

As long as it is mostly me doing development on this as a solo dev working on the app in my free time, I unfortunately do not have the resources to manage this, especially considering the app's architecture was not laid out with sync in mind.

Thanks for your understanding.
